version: '3.8'

services:

  database:
    container_name: database
    image: mysql:${MYSQL_VERSION}
    command: --default-authantication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped

